version: 2
jobs:
  build:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run:
          name: "Update NPM"
          command: 'sudo npm install -g npm@latest'
      - run:
          name: "Install Client Dependencies"
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
workflows:
  version: 2
  build:
    jobs:
      - build
