version: 2
jobs:
  build:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run:
          name: "Update NPM"
          command: 'sudo npm install -g npm@latest'
      - run:
          name: "Install Client Dependencies"
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: "Client Lint Check"
          command: "npm run lint"
      - run:
          name: "Flow Client Code Coverage"
          command: npm run flow:ci
      - run:
          name: "Run Client Tests"
          command: npm run test --ci --runInBand --testResultsProcessor="jest-junit"
          environment:
            JEST_JUNIT_OUTPUT: "reports/jest/results.xml"
      - store_test_results:
          path: reports
workflows:
  version: 2
  build:
    jobs:
      - build
